---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongo-db-deployment
  labels:
    name: mongo-db
    type: database
    intent: local-dev
spec:
  selector:
    matchLabels:
      app: mongoDBContainer
      type: database
      env: local
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongoDBContainer
        type: database
        env: local
    spec:
      containers:
      - name:  mongo-db-deployment
        image:  mongo:latest@sha256:d341a86584b96eb665345a8f5b35fba8695ee1d0618fd012ec4696223a3d6c62
        resources:
          requests:
            cpu: '1'
            memory: 4Gi
          limits:
            cpu: '1'
            memory: 4Gi
        # env:
        #   - name: MONGO_INITDB_ROOT_USERNAME
        #     value: mongo-db-admin
        #   - name: MONGO_INITDB_ROOT_PASSWORD
        #     value: 'axc6nhz5nbp8mnp'
        #   - name: MONGO_INITDB_DATABASE
        #     value: testing
        ports:
          - containerPort: 27017
            name: mongo-db-port
        volumeMounts:
        - name: empty
          mountPath: /tmp/mongo
      volumes:
        - name: empty
          emptyDir: {}
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name:  mongo-db-service
spec:
  selector:
    app: mongoDBContainer
    type: database
    env: local
  type:  NodePort
  ports:
  - name:  mongodb-port
    nodePort: 30001
    targetPort: mongo-db-port
    port: 9999